### ISSUE TITLE
Update website 

### ISSUE THREAD

**Issue by EmmaJiaXue** [bdsjuoft/bdsjuoft.github.io#12]
PEOPLE:
add, https://www.ishtiaque.net/

PUBLICATION

1： Physical assault perpetration and victimisation among Chinese university students
[CJSW2019XUE.pdf](https://github.com/bdsjuoft/bdsjuoft.github.io/files/3660668/CJSW2019XUE.pdf)

![sLDW9869232](https://user-images.githubusercontent.com/34752770/65741087-f88b6500-e0b8-11e9-9bd9-ffe80ae01626.jpg)

2： Using social media to explore the linguistic features in female adults with childhood sexual abuse by Linguistic Inquiry and Word Count
![9733284483_d01e4924cb_k](https://user-images.githubusercontent.com/34752770/65740972-95013780-e0b8-11e9-9f7c-60706b4bfdcb.jpg)

[HBET_xue2019.pdf](https://github.com/bdsjuoft/bdsjuoft.github.io/files/3660783/HBET_xue2019.pdf)

3： Harnessing big data for social justice: An exploration of violence against women‐related conversations on Twitter
![Big-Data](https://user-images.githubusercontent.com/34752770/65740910-58cdd700-e0b8-11e9-8544-8f9591d32699.jpeg)

[Xue_et_al-2019HBET.pdf](https://github.com/bdsjuoft/bdsjuoft.github.io/files/3660784/Xue_et_al-2019HBET.pdf)

**Comment by EmmaJiaXue** [comment]
Homepage
https://web.cs.toronto.edu/news-events/news/2019-connaught-new-researcher-award-winners-announced

post this.

**Comment by panchercc** [comment]
A good web reference:
https://wanglab.ml/index.html
