### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by EmmaJiaXue** [bdsjuoft/bdsjuoft.github.io#2]
Domain name to be determined

@EmmaJiaXue will propose a few options

**Comment by panchercc** [comment]
The current domain name `http://bigdatasocialjustice.utoronto.ca` is too long and difficult for people to remember. Let us come up with a better name.

**Comment by panchercc** [comment]
`http://AIJ.utoronto.ca`

`AIJ` is short for **A**rtificial **I**ntelligence for social **J**ustice. Also, it is related to Jia's name.
